name: Lint and Scan Docker

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  lint-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Local Container Image
        run: docker build -t local/pg-es-logstash:latest .
      - uses: anchore/scan-action@v2
        with:
          image: "local/pg-es-logstash:latest"
          severity-cutoff: "high"
          fail-build: false
          acs-report-enable: true
      - name: Inspect action SARIF report
        run: cat ${{ steps.scan.outputs.sarif }}